Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-10.2"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |provider|
    provider.name = "pmevo-artifact"
    provider.memory = 8096
    provider.cpus = 4
    # provider.memory = 2048
    # provider.cpus = 2
  end
  config.vm.network :forwarded_port, guest: 80, host: 8080
end

